### ISSUE TITLE
[Assignment 08] Broken MIR ... rust compiler bug(?) unexpectedly

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs220#159]
Hello, Now i'm doing HW8.
While i'm writing code for pub fn repeat, I got a rust compiler bug error message, but i'm not sure this is really rust compiler bug. So could you please check this issue so i can report on rust repository?
My idea was, calling closure recursively on repeat function.
So there is line like this on my code:
`repeat(n - 1, |x| f(x))` 
This line caused some error message like this:
```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in DefId(0:172 ~ cs220[d780]::assignments::assignment08::repeat) (Terminator { source_info: SourceInfo { span: src/assignments/assignment08.rs:16:5: 16:28 (#0), scope: scope[0] }, kind: _0 = assignment08::repeat::<T, [closure@src/assignments/assignment08.rs:16:19: 16:27]>(move _7, move _10) -> [return: bb4, unwind: bb6] }): call dest mismatch (impl FnMut(T) -> T <- impl FnMut(T) -> T): NoSolution
  --> src/assignments/assignment08.rs:16:26
   |
16 |     repeat(n - 1, |x| f(x))
   |                          ^
   |
   = note: delayed at compiler/rustc_borrowck/src/type_check/mod.rs:1570:21

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1425:13
stack backtrace:
   0:        0x109f9ffe0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h188b7ef1c7993e78
   1:        0x109ff1a54 - core::fmt::write::he84a3004e7af3f34
   2:        0x109f930c0 - std::io::Write::write_fmt::h9370b50affaab0be
   3:        0x109fa2c24 - std::panicking::default_hook::{{closure}}::hc074f8023cce83ca
   4:        0x109fa298c - std::panicking::default_hook::hef854b51b9b79ff2
   5:        0x102584154 - rustc_driver[8d2050f8429f7bc4]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:        0x109fa31f8 - std::panicking::rust_panic_with_hook::h1e59e224d558a492
   7:        0x1061d2350 - std[ad4c17a2ddbcabe2]::panicking::begin_panic::<rustc_errors[3321b68084f70bb0]::ExplicitBug>::{closure#0}
   8:        0x1061cf4f4 - std[ad4c17a2ddbcabe2]::sys_common::backtrace::__rust_end_short_backtrace::<std[ad4c17a2ddbcabe2]::panicking::begin_panic<rustc_errors[3321b68084f70bb0]::ExplicitBug>::{closure#0}, !>
   9:        0x1064dc7ec - std[ad4c17a2ddbcabe2]::panicking::begin_panic::<rustc_errors[3321b68084f70bb0]::ExplicitBug>
  10:        0x1061f64e8 - std[ad4c17a2ddbcabe2]::panic::panic_any::<rustc_errors[3321b68084f70bb0]::ExplicitBug>
  11:        0x1061fa430 - <rustc_errors[3321b68084f70bb0]::HandlerInner as core[bae5e8ef542d20e5]::ops::drop::Drop>::drop
  12:        0x10251be00 - core[bae5e8ef542d20e5]::ptr::drop_in_place::<rustc_session[282d64e95cd3bf88]::parse::ParseSess>
  13:        0x1025235ec - <alloc[60e9ff9c62c1e93b]::rc::Rc<rustc_session[282d64e95cd3bf88]::session::Session> as core[bae5e8ef542d20e5]::ops::drop::Drop>::drop
  14:        0x1025215dc - core[bae5e8ef542d20e5]::ptr::drop_in_place::<rustc_interface[db32075e2a9c594e]::interface::Compiler>
  15:        0x102515c9c - rustc_span[143ffa354e326ede]::with_source_map::<core[bae5e8ef542d20e5]::result::Result<(), rustc_errors[3321b68084f70bb0]::ErrorGuaranteed>, rustc_interface[db32075e2a9c594e]::interface::create_compiler_and_run<core[bae5e8ef542d20e5]::result::Result<(), rustc_errors[3321b68084f70bb0]::ErrorGuaranteed>, rustc_driver[8d2050f8429f7bc4]::run_compiler::{closure#1}>::{closure#1}>
  16:        0x102529fe8 - <scoped_tls[e8c526b3ddc66487]::ScopedKey<rustc_span[143ffa354e326ede]::SessionGlobals>>::set::<rustc_interface[db32075e2a9c594e]::interface::run_compiler<core[bae5e8ef542d20e5]::result::Result<(), rustc_errors[3321b68084f70bb0]::ErrorGuaranteed>, rustc_driver[8d2050f8429f7bc4]::run_compiler::{closure#1}>::{closure#0}, core[bae5e8ef542d20e5]::result::Result<(), rustc_errors[3321b68084f70bb0]::ErrorGuaranteed>>
  17:        0x102574b68 - std[ad4c17a2ddbcabe2]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[db32075e2a9c594e]::util::run_in_thread_pool_with_globals<rustc_interface[db32075e2a9c594e]::interface::run_compiler<core[bae5e8ef542d20e5]::result::Result<(), rustc_errors[3321b68084f70bb0]::ErrorGuaranteed>, rustc_driver[8d2050f8429f7bc4]::run_compiler::{closure#1}>::{closure#0}, core[bae5e8ef542d20e5]::result::Result<(), rustc_errors[3321b68084f70bb0]::ErrorGuaranteed>>::{closure#0}, core[bae5e8ef542d20e5]::result::Result<(), rustc_errors[3321b68084f70bb0]::ErrorGuaranteed>>
  18:        0x102548ef8 - <<std[ad4c17a2ddbcabe2]::thread::Builder>::spawn_unchecked_<rustc_interface[db32075e2a9c594e]::util::run_in_thread_pool_with_globals<rustc_interface[db32075e2a9c594e]::interface::run_compiler<core[bae5e8ef542d20e5]::result::Result<(), rustc_errors[3321b68084f70bb0]::ErrorGuaranteed>, rustc_driver[8d2050f8429f7bc4]::run_compiler::{closure#1}>::{closure#0}, core[bae5e8ef542d20e5]::result::Result<(), rustc_errors[3321b68084f70bb0]::ErrorGuaranteed>>::{closure#0}, core[bae5e8ef542d20e5]::result::Result<(), rustc_errors[3321b68084f70bb0]::ErrorGuaranteed>>::{closure#1} as core[bae5e8ef542d20e5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  19:        0x109faba5c - std::sys::unix::thread::Thread::new::thread_start::h7b2f9b83fb320a20
  20:        0x184a03878 - _pthread_jit_write_protect_np

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0 (4b91a6ea7 2022-08-08) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```
Thank you.

**Comment by tomtomjhj** [comment]
Can you try the latest version of rust? In `rust-toolchain` file, replace `1.63.0` with `1.65.0`.

**Comment by junsooo** [comment]
Thank you. That compiler error issue is solved.
