### ISSUE TITLE
can't connect to server

### ISSUE THREAD

**Issue by tkd992006** [kaist-cp/cs220#23]
I can connect to server using ssh commands through terminal, but if i try to connect to server using remote development, remote - ssh, i can choose OS, and type password. but after then, these error happens and can't connect to server.
 so how can i connect to server through remote- ssh?

```
[03:11:18.980] Log Level: 2
[03:11:18.982] remote-ssh@0.84.0
[03:11:18.983] win32 x64
[03:11:18.998] SSH Resolver called for "ssh-remote+cs220", attempt 1
[03:11:18.999] "remote.SSH.useLocalServer": false
[03:11:19.000] "remote.SSH.showLoginTerminal": false
[03:11:19.000] "remote.SSH.remotePlatform": {"172.10.9.39":"linux"}
[03:11:19.000] "remote.SSH.path": undefined
[03:11:19.000] "remote.SSH.configFile": undefined
[03:11:19.001] "remote.SSH.useFlock": true
[03:11:19.001] "remote.SSH.lockfilesInTmp": false
[03:11:19.001] "remote.SSH.localServerDownload": auto
[03:11:19.001] "remote.SSH.remoteServerListenOnSocket": false
[03:11:19.001] "remote.SSH.showLoginTerminal": false
[03:11:19.002] "remote.SSH.defaultExtensions": []
[03:11:19.002] "remote.SSH.loglevel": 2
[03:11:19.002] "remote.SSH.enableDynamicForwarding": true
[03:11:19.002] "remote.SSH.enableRemoteCommand": false
[03:11:19.002] "remote.SSH.serverPickPortsFromRange": {}
[03:11:19.002] "remote.SSH.serverInstallPath": {}
[03:11:19.053] SSH Resolver called for host: cs220
[03:11:19.053] Setting up SSH remote "cs220"
[03:11:19.062] Using commit id "784b0177c56c607789f9638da7b6bf3230d47a8c" and quality "stable" for server
[03:11:19.073] Install and start server if needed
[03:11:20.445] Checking ssh with "ssh -V"
[03:11:20.506] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[03:11:20.511] Remote command length: 6205/8192 characters
[03:11:20.511] Running script with connection command: ssh -T -D 1410 cs220 powershell
[03:11:20.516] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[03:11:20.775] > ]0;C:\WINDOWS\System32\cmd.exe
[03:11:20.776] Got some output, clearing connection timeout
[03:11:20.911] > s20180451@cp-service.kaist.ac.kr's password: 
[03:11:20.912] Showing password prompt
[03:11:24.450] Got password response
[03:11:24.450] "install" wrote data to terminal: "***********"
[03:11:24.466] > 
[03:11:24.647] > bash: line 1: powershell: command not found
[03:11:25.942] "install" terminal command done
[03:11:25.943] Install terminal quit with output: bash: line 1: powershell: command not found
[03:11:25.943] Received install output: bash: line 1: powershell: command not found
[03:11:25.944] Failed to parse remote port from server output
[03:11:25.944] Resolver error: Error: 
	at g.Create (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:585222)
	at t.handleInstallOutput (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:583874)
	at t.tryInstall (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:681023)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:643908
	at async t.withShowDetailsEvent (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:647224)
	at async t.resolve (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:644958)
	at async c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:727082
[03:11:25.954] ------
```

**Comment by buttercrab** [comment]
You have to choose linux for OS, not Windows.
