### ISSUE TITLE
[Assignment #] (SUMMARIZE YOUR QUESTION AS CLEARLY AS POSSIBLE)

### ISSUE THREAD

**Issue by kokorea** [kaist-cp/cs220#271]
### Googling Result

https://bonita-sy.tistory.com/entry/VSCode-%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4%EC%97%90%EC%84%9C-%EC%97%86%EB%8A%94-%ED%8C%8C%EC%9D%B4%ED%94%84%EC%97%90-%EC%93%B0%EB%A0%A4%EA%B3%A0-%ED%96%88%EC%8A%B5%EB%8B%88%EB%8B%A4-The-process-tried-to-write-to-a-nonexistent-pi

https://goldenboylife.synology.me/wordpress/?p=6249

### ChatGPT Result

https://chat.openai.com/share/36a35989-8754-42bd-b859-ac9d1571cdbc

### Your question here

```
[20:30:11.795] Log Level: 2
[20:30:12.313] SSH Resolver called for "ssh-remote+coder-vscode--20210201--hyunu", attempt 1
[20:30:12.313] "remote.SSH.useLocalServer": false
[20:30:12.314] "remote.SSH.useExecServer": false
[20:30:12.314] "remote.SSH.showLoginTerminal": false
[20:30:12.314] "remote.SSH.remotePlatform": {}
[20:30:12.314] "remote.SSH.path": undefined
[20:30:12.315] "remote.SSH.configFile": undefined
[20:30:12.315] "remote.SSH.useFlock": true
[20:30:12.315] "remote.SSH.lockfilesInTmp": false
[20:30:12.315] "remote.SSH.localServerDownload": auto
[20:30:12.316] "remote.SSH.remoteServerListenOnSocket": false
[20:30:12.316] "remote.SSH.showLoginTerminal": false
[20:30:12.316] "remote.SSH.defaultExtensions": []
[20:30:12.317] "remote.SSH.loglevel": 2
[20:30:12.317] "remote.SSH.enableDynamicForwarding": true
[20:30:12.317] "remote.SSH.enableRemoteCommand": false
[20:30:12.317] "remote.SSH.serverPickPortsFromRange": {}
[20:30:12.319] "remote.SSH.serverInstallPath": {}
[20:30:12.326] VS Code version: 1.82.2
[20:30:12.326] Remote-SSH version: remote-ssh@0.106.4
[20:30:12.326] win32 x64
[20:30:12.332] SSH Resolver called for host: coder-vscode--20210201--hyunu
[20:30:12.332] Setting up SSH remote "coder-vscode--20210201--hyunu"
[20:30:12.341] Using commit id "abd2f3db4bdb28f9e95536dfa84d8479f1eb312d" and quality "stable" for server
[20:30:12.353] Install and start server if needed
[20:30:14.328] Checking ssh with "C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe -V"
[20:30:14.338] Got error from ssh: spawn C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[20:30:14.340] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe -V"
[20:30:14.343] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[20:30:14.344] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[20:30:14.347] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[20:30:14.348] Checking ssh with "C:\Windows\ssh.exe -V"
[20:30:14.351] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[20:30:14.352] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[20:30:14.356] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[20:30:14.358] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[20:30:14.362] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[20:30:14.363] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[20:30:14.570] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[20:30:14.583] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 57980 "coder-vscode--20210201--hyunu" bash
[20:30:14.588] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[20:30:17.628] > ssh: Could not resolve hostname coder-vscode--20210201--hyunu: \276\313\267\301\301\370 \310\243\275\272\306\256\260\241 \276\370\275\300\264\317\264\331.
> 프로세스에서 없는 파이프에 쓰려고 했습니다.
> ]0;C:\WINDOWS\System32\cmd.exe
[20:30:17.630] Got some output, clearing connection timeout
[20:30:18.973] "install" terminal command done
[20:30:18.981] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[20:30:18.984] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[20:30:18.987] Failed to parse remote port from server output
[20:30:18.999] Resolver error: Error: 
	at g.Create (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:637879)
	at t.handleInstallOutput (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:635279)
	at t.tryInstall (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:756878)
	at async c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:717470
	at async t.withShowDetailsEvent (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:720723)
	at async C (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:714384)
	at async t.resolve (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:718119)
	at async c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:901789
```

This is my error message and I deleted the `known_hosts` files as followed by google result and I removed vscode and i install again but same error keep happening. Is there any solutions for this problem?

**Comment by kokorea** [comment]
After I restart my computer the error was fixed. sorry for interrupting.
