### ISSUE TITLE
[Assignment 13] Inconsistencies in test results caused by testing in parallel.

### ISSUE THREAD

**Issue by cotton-lemon** [kaist-cp/cs220#439]
### Googling Result

https://stackoverflow.com/questions/54501943/consecutive-unit-tests-fail-although-they-succeed-individually
https://www.reddit.com/r/csharp/comments/129skx7/help_please_a_test_passes_when_run_individually/

### ChatGPT Result

https://chatgpt.com/share/67581f1d-8374-8011-b607-35622aa3802a

### Your question here

There is inconsistency with result of tests due to the all tests run in  parallel. 
When I tested each test individually, they all passed. However when I tested with grade.sh , vec_add_test,dot_product_test failed. Some times they passed, but sometimes they failed in performance test. Followings are some result of tests at developer server.

```
vec_add

individual test -pass
---- assignments::assignment13::small_exercises_grade::test::vec_add_test stdout ----
vecadd Sequential: 97.362398ms, Parallel: 42.21125ms
vecadd Sequential: 90.040766ms, Parallel: 20.152095ms
vecadd Sequential: 93.662383ms, Parallel: 23.204567ms
vecadd Sequential: 92.66967ms, Parallel: 18.210259ms
vecadd Sequential: 92.355957ms, Parallel: 21.494218ms


run 1 -fail
---- assignments::assignment13::small_exercises_grade::test::vec_add_test stdout ----
vecadd Sequential: 89.255318ms, Parallel: 19.173723ms
vecadd Sequential: 95.075517ms, Parallel: 18.282158ms
vecadd Sequential: 187.92723ms, Parallel: 273.967112ms
thread 'assignments::assignment13::small_exercises_grade::test::vec_add_test' panicked at src/assignments/assignment13/small_exercises_grade.rs:108:13:
Sequential: 187.92723ms, Parallel: 273.967112ms


run2 -fail
---- assignments::assignment13::small_exercises_grade::test::vec_add_test stdout ----
vecadd Sequential: 92.657505ms, Parallel: 18.755546ms
vecadd Sequential: 90.459191ms, Parallel: 13.867652ms
vecadd Sequential: 251.0564ms, Parallel: 283.972671ms
thread 'assignments::assignment13::small_exercises_grade::test::vec_add_test' panicked at src/assignments/assignment13/small_exercises_grade.rs:108:13:
Sequential: 251.0564ms, Parallel: 283.972671ms

run3 -fail
---- assignments::assignment13::small_exercises_grade::test::vec_add_test stdout ----
vecadd Sequential: 89.802444ms, Parallel: 26.872207ms
vecadd Sequential: 89.378884ms, Parallel: 22.908779ms
vecadd Sequential: 138.486557ms, Parallel: 475.938446ms
thread 'assignments::assignment13::small_exercises_grade::test::vec_add_test' panicked at src/assignments/assignment13/small_exercises_grade.rs:108:13:
Sequential: 138.486557ms, Parallel: 475.938446ms

run without performance test
---- assignments::assignment13::small_exercises_grade::test::vec_add_test stdout ----
vecadd Sequential: 94.805785ms, Parallel: 24.050593ms
vecadd Sequential: 93.596535ms, Parallel: 18.411336ms
vecadd Sequential: 178.109838ms, Parallel: 411.759562ms
vecadd Sequential: 91.871241ms, Parallel: 16.685551ms
vecadd Sequential: 91.793624ms, Parallel: 14.460275ms


dot product

individual test - pass
---- assignments::assignment13::small_exercises_grade::test::dot_product_test stdout ----
dot product Sequential: 92.739449ms, Parallel: 21.330762ms
dot product Sequential: 178.69436ms, Parallel: 17.758548ms
dot product Sequential: 90.209312ms, Parallel: 20.490816ms
dot product Sequential: 89.166213ms, Parallel: 27.50542ms
dot product Sequential: 105.247373ms, Parallel: 24.457104ms

run1 -pass
---- assignments::assignment13::small_exercises_grade::test::dot_product_test stdout ----
dot product Sequential: 89.105264ms, Parallel: 22.028318ms
dot product Sequential: 119.875689ms, Parallel: 23.995462ms
dot product Sequential: 88.981019ms, Parallel: 19.64144ms
dot product Sequential: 89.294521ms, Parallel: 20.777656ms
dot product Sequential: 165.464617ms, Parallel: 61.873089ms

run2 - fail
---- assignments::assignment13::small_exercises_grade::test::dot_product_test stdout ----
dot product Sequential: 88.715741ms, Parallel: 22.446754ms
dot product Sequential: 121.114816ms, Parallel: 600.271079ms
thread 'assignments::assignment13::small_exercises_grade::test::dot_product_test' panicked at src/assignments/assignment13/small_exercises_grade.rs:147:13:
Sequential: 121.114816ms, Parallel: 600.271079ms

run without performance test
---- assignments::assignment13::small_exercises_grade::test::dot_product_test stdout ----
dot product Sequential: 89.355486ms, Parallel: 21.703826ms
dot product Sequential: 137.205257ms, Parallel: 550.965381ms
dot product Sequential: 90.07845ms, Parallel: 20.288697ms
dot product Sequential: 102.757153ms, Parallel: 551.665873ms
dot product Sequential: 88.515442ms, Parallel: 83.477049ms
```

For vec_add test, when test with grade.sh, it always failed in 3rd iteration of for loop (when failed). It is slower about 15x than 1st,2nd iteration. Also the sequential version was slower 2x in 3rd iteration. There is no reason to 3rd iteration to be much slower than 1st,2nd, because loop variable doesn't affect the test.
When test all tests sequentially with "cargo test --  assignments::assignment13::small_exercises_grade --show-output  --test-threads=1", it always passed.
It is intended to each test affect the other?

**Comment by Lee-Janggun** [comment]
Does it pass in gg?

**Comment by cotton-lemon** [comment]
> Does it pass in gg?

No. I tried 4times and vec_add_test always failed.
Submit Id is 29301.

By the way, when I changed the implementation of  vec_add and doc_product in assignment9, the phenomenon didn't occur. It always passed the all tests.

**Comment by Lee-Janggun** [comment]
Hmm... I'm honestly not sure. It's very weird that the result of parallel execution is that different. If changing assignment9
 makes it work I suggest you go with that.

**Comment by tejava9929** [comment]
I experienced a similar phenomenon in my case. The test passed stably in my development server, but not in gg. After modifying the implementation of assignment9, the problem solved.

**Comment by aquacat1220** [comment]
Same problem here too. It feels odd to *slow down* assignment 9 to make sure assignment 13 passes..

**Comment by Jaewookim08** [comment]
@cotton-lemon @aquacat1220  We would appreciate it if you could email us both your passing and non-passing code so that we can troubleshoot.
