### ISSUE TITLE
[Homework 4] What should be in assignment04.zip?

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs220#46]
Hi,
I have uploaded my solution on gg.kaist.ac.kr, but the log says
I have 'not yet implemented' for all three functions.

What I have done is I have compressed the folder that contains context.rs, mod.rs, parser.rs, syntax.pest, and syntax.rs into a zip file and submitted on gg.
Am I following the correct format?

**Comment by zzz845zz** [comment]
That's right. `context.rs, mod.rs, parser.rs, syntax.pest, syntax.rs` should be in `assignment04.zip`.

Could you please check your code in the zip and submit it again? 
And please show your full log if the same error still happens.

**Comment by choejms** [comment]
===== CHECK =====
[2022-09-16 15:40:04,015: WARNING/ForkPoolWorker-32] Demoting to runner...
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.63.0 (4b91a6ea7 2022-08-08)


Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source "$HOME/.cargo/env"
Cloning into 'cs220'...
Archive:  ../submission
   creating: src/assignments/assignment04/assignment04/
  inflating: src/assignments/assignment04/assignment04/syntax.pest  
  inflating: src/assignments/assignment04/assignment04/mod.rs  
  inflating: src/assignments/assignment04/assignment04/syntax.rs  
  inflating: src/assignments/assignment04/assignment04/parser.rs  
  inflating: src/assignments/assignment04/assignment04/context.rs  
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.63.0 (4b91a6ea7 2022-08-08)

info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.65.0-nightly (cf9ed0dd5 2022-09-15)

info: checking for self-updates
    Updating crates.io index
   Compiling proc-macro2 v1.0.43
   Compiling quote v1.0.21
   Compiling unicode-ident v1.0.4
   Compiling syn v1.0.99
   Compiling version_check v0.9.4
   Compiling thiserror v1.0.35
   Compiling autocfg v1.1.0
   Compiling ucd-trie v0.1.5
   Compiling libc v0.2.132
   Compiling once_cell v1.14.0
   Compiling heck v0.4.0
   Compiling anyhow v1.0.65
    Checking os_str_bytes v6.3.0
    Checking hashbrown v0.12.3
    Checking termcolor v1.1.3
    Checking strsim v0.10.0
    Checking textwrap v0.15.1
    Checking bitflags v1.3.2
    Checking either v1.8.0
    Checking lazy_static v1.4.0
    Checking etrace v1.1.1
    Checking itertools v0.10.4
    Checking clap_lex v0.2.4
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.9.1
    Checking atty v0.2.14
   Compiling thiserror-impl v1.0.35
   Compiling clap_derive v3.2.18
   Compiling pest v2.3.1
    Checking clap v3.2.22
   Compiling pest_meta v2.3.1
   Compiling pest_generator v2.3.1
   Compiling pest_derive v2.3.1
    Checking cs220 v0.1.0 (/app/files/checks/7b8d4660-4e48-4a80-86ee-ea64202b1614/cs220)
    Finished dev [unoptimized + debuginfo] target(s) in 13.63s
Running with cargo...

running 3 tests
test assignments::assignment04_grade::test::test_parse ... FAILED
test assignments::assignment04_grade::test::test_context_calc_expression ... FAILED
test assignments::assignment04_grade::test::test_context_calc_command ... FAILED

failures:

---- assignments::assignment04_grade::test::test_parse stdout ----
thread 'assignments::assignment04_grade::test::test_parse' panicked at 'not yet implemented: fill here', src/assignments/assignment04/parser.rs:24:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- assignments::assignment04_grade::test::test_context_calc_expression stdout ----
thread 'assignments::assignment04_grade::test::test_context_calc_expression' panicked at 'not yet implemented: fill here', src/assignments/assignment04/context.rs:29:9

---- assignments::assignment04_grade::test::test_context_calc_command stdout ----
thread 'assignments::assignment04_grade::test::test_context_calc_command' panicked at 'not yet implemented: fill here', src/assignments/assignment04/context.rs:44:9


failures:
    assignments::assignment04_grade::test::test_context_calc_command
    assignments::assignment04_grade::test::test_context_calc_expression
    assignments::assignment04_grade::test::test_parse

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 20 filtered out; finished in 0.00s

[0;31m[1mTest failed:    cargo test  --lib assignment04_grade[0m

**Comment by choejms** [comment]
I made sure that codes are up to date, and it still says 'not yet implemented: fill here' error.
The code passes all cases on my personal laptop.

Thank you

**Comment by choejms** [comment]
+ I also made sure the code passes all cases on the serve as well.

**Comment by choejms** [comment]
Oh my god I just found the error.
The error was I put all files in a folder called assignment04 and compressed the folder,
instead of compressing the files directly..

Sorry for this haha

**Comment by m-spitfire** [comment]
@choejms , you can use the convenient script `./scripts/prepare-submissions.sh` then submit `./target/assignment04.zip` next time
